---
resource_types:
- name: datetime-version
  type: registry-image
  source:
    repository: dcsg/datetime-version-resource

resources:
- name: datetime-version
  type: datetime-version
  icon: tag-plus
  source:
    timezone: 'America/New_York'

- type: git
  name: source
  icon: github
  source:
    uri: ((resources.source_uri))
    branch: main
    private_key: ((github.private_key))

# Where we will push the image to
- name: ocibuild-image
  type: registry-image
  icon: robot-industrial
  source:
    repository: concourse/oci-build-task

- name: fluentd-base
  type: registry-image
  icon: docker
  source:
    repository: ((docker.repository.base))
    username: ((docker.username))
    password: ((docker.password))
    tag: latest

- name: fluentd-custom
  type: registry-image
  icon: docker
  source:
    repository: ((docker.repository.custom))
    username: ((docker.username))
    password: ((docker.password))
    tag: latest

jobs:
- name: build-and-ship
  public: true
  serial: true
  plan:
  - in_parallel:
    - get: source
      trigger: true
    - get: ocibuild-image
    - get: fluentd-base
      trigger: true
  - task: build
    image: ocibuild-image
    privileged: true
    config:
      platform: linux
      params:
        CONTEXT: source
      inputs: [{name: source}]
      outputs: [{name: image}]
      caches: [{path: cache}]
      run: {path: build}
  - put: datetime-version
  - put: fluentd-custom
    params:
      image: image/image.tar
      additional_tags: datetime-version/version

...